version: '3'
services:
  cassandra-node1:
    image: cassandra:5
    container_name: cassandra-node1
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - ./cassandra/node1:/var/lib/cassandra

  cassandra-node2:
    image: cassandra:5
    container_name: cassandra-node2
    ports:
      - 9142:9042
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - ./cassandra/node2:/var/lib/cassandra
    depends_on:
      - cassandra-node1
